spring:
  application:
    name: nacos-provider
  profiles:
    active: dev
  cloud:
   nacos:
      discovery:
        server-addr: 192.168.0.108:8848
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.108:3306/edu_bit_shop?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      enabled: true
      exclude: WEB-INF/**
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.shop.course.*.entity

#showSql
logging:
  level:
    com:
      shop:
        course : debug